# Generated by Django 5.1.7 on 2025-03-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cleanliness',
            field=models.CharField(blank=True, choices=[('Messy', 'Messy'), ('Average', 'Average'), ('Clean', 'Clean')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_preference',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='loudness',
            field=models.CharField(blank=True, choices=[('Quiet', 'Quiet'), ('Moderate', 'Moderate'), ('Loud', 'Loud')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
    ]
